version: "3"
services:
  bodyposenet-camera:
    container_name: bodyposenet-camera
    privileged: yes
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app/mnt
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
        #      - /opt/nvidia/:/opt/nvidia/
    environment:
      - DISPLAY
      - CUDA_VER=10.2
      - LD_LIBRARY_PATH=/opt/nvidia/deepstream/deepstream/lib/cvcore_libs
    network_mode: host
    working_dir: /app/src
    tty: true

